apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: myapp-replicasetcaset
spec:
   template:
      metadata:
         name: nginx-deployment
         labels:
            app: myapp
            type: restapi
            
      spec:
         containers:
            - name: simple-api
              image: nginx
   replicas: 6
   selector:
      matchLabels:
         app: myapp
         type: restapi